service: hackathon-service

provider:
  name: aws
  runtime: java11
  region: ${opt:stage, 'ap-southeast-2'}
  stage: ${opt:stage, 'dev'}

package:
  artifact: target/hackathon.jar

functions:
  createTransaction:
    handler: com.thirdparty.LambdaHandler::handleRequest
    role: LambdaRole
    events:
      - http:
          path: transaction/create
          method: post
          cors: true
  searchTransactions:
    handler: com.thirdparty.LambdaHandler::handleRequest
    role: LambdaRole
    events:
      - http:
          path: transaction/fetch
          method: post
          cors: true
  createWallet:
    handler: com.thirdparty.LambdaHandler::handleRequest
    role: LambdaRole
    events:
      - http:
          path: wallet/create
          method: post
          cors: true
  searchWallets:
    handler: com.thirdparty.LambdaHandler::handleRequest
    role: LambdaRole
    events:
      - http:
          path: wallet/fetch
          method: post
          cors: true
  getHotel:
    handler: com.thirdparty.LambdaHandler::handleRequest
    role: LambdaRole
    events:
      - http:
          path: hotel/{id}
          method: get
          cors: true
  getPartner:
    handler: com.thirdparty.LambdaHandler::handleRequest
    role: LambdaRole
    events:
      - http:
          path: partner/{id}
          method: get
          cors: true
  login:
    handler: com.thirdparty.LambdaHandler::handleRequest
    role: LambdaRole
    events:
      - http:
          path: auth/login
          method: post
          cors: true

resources:
  Resources:
    DDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hackathon-third-party
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    LambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: hackathon-lambda-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: hackathon-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: Allow
                  Action:
                    - dynamodb:*
                  Resource: '*'
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'